package model;
// Generated 04-ene-2016 15:44:54 by Hibernate Tools 4.3.1



/**
 * Erabiltzailea generated by hbm2java
 */
public class Erabiltzailea  implements java.io.Serializable {


     private String erabIzena;
     private String izena;
     private String pasahitza;
     private String rola;
     private String kontuKorrontea;

    public Erabiltzailea() {
    }

    public Erabiltzailea(String erabIzena, String izena, String pasahitza, String rola, String kontuKorrontea) {
       this.erabIzena = erabIzena;
       this.izena = izena;
       this.pasahitza = pasahitza;
       this.rola = rola;
       this.kontuKorrontea = kontuKorrontea;
    }
   
    public String getErabIzena() {
        return this.erabIzena;
    }
    
    public void setErabIzena(String erabIzena) {
        this.erabIzena = erabIzena;
    }
    public String getIzena() {
        return this.izena;
    }
    
    public void setIzena(String izena) {
        this.izena = izena;
    }
    public String getPasahitza() {
        return this.pasahitza;
    }
    
    public void setPasahitza(String pasahitza) {
        this.pasahitza = pasahitza;
    }
    public String getRola() {
        return this.rola;
    }
    
    public void setRola(String rola) {
        this.rola = rola;
    }
    public String getKontuKorrontea() {
        return this.kontuKorrontea;
    }
    
    public void setKontuKorrontea(String kontuKorrontea) {
        this.kontuKorrontea = kontuKorrontea;
    }




}


