package model;
// Generated 04-ene-2016 15:44:54 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Erreserba generated by hbm2java
 */
public class Erreserba  implements java.io.Serializable {


     private int erreserbaId;
     private Date erreserbaDate;
     private boolean ordaindua;
     private String telefonoa;
     private String kontaktuIzena;

    public Erreserba() {
    }

    public Erreserba(int erreserbaId, Date erreserbaDate, boolean ordaindua, String telefonoa, String kontaktuIzena) {
       this.erreserbaId = erreserbaId;
       this.erreserbaDate = erreserbaDate;
       this.ordaindua = ordaindua;
       this.telefonoa = telefonoa;
       this.kontaktuIzena = kontaktuIzena;
    }
   
    public int getErreserbaId() {
        return this.erreserbaId;
    }
    
    public void setErreserbaId(int erreserbaId) {
        this.erreserbaId = erreserbaId;
    }
    public Date getErreserbaDate() {
        return this.erreserbaDate;
    }
    
    public void setErreserbaDate(Date erreserbaDate) {
        this.erreserbaDate = erreserbaDate;
    }
    public boolean isOrdaindua() {
        return this.ordaindua;
    }
    
    public void setOrdaindua(boolean ordaindua) {
        this.ordaindua = ordaindua;
    }
    public String getTelefonoa() {
        return this.telefonoa;
    }
    
    public void setTelefonoa(String telefonoa) {
        this.telefonoa = telefonoa;
    }
    public String getKontaktuIzena() {
        return this.kontaktuIzena;
    }
    
    public void setKontaktuIzena(String kontaktuIzena) {
        this.kontaktuIzena = kontaktuIzena;
    }




}


