package model;
// Generated 04-ene-2016 15:44:54 by Hibernate Tools 4.3.1



/**
 * EskaintzaId generated by hbm2java
 */
public class EskaintzaId  implements java.io.Serializable {


     private int landetxeaId;
     private int eskaintzaId;

    public EskaintzaId() {
    }

    public EskaintzaId(int landetxeaId, int eskaintzaId) {
       this.landetxeaId = landetxeaId;
       this.eskaintzaId = eskaintzaId;
    }
   
    public int getLandetxeaId() {
        return this.landetxeaId;
    }
    
    public void setLandetxeaId(int landetxeaId) {
        this.landetxeaId = landetxeaId;
    }
    public int getEskaintzaId() {
        return this.eskaintzaId;
    }
    
    public void setEskaintzaId(int eskaintzaId) {
        this.eskaintzaId = eskaintzaId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof EskaintzaId) ) return false;
		 EskaintzaId castOther = ( EskaintzaId ) other; 
         
		 return (this.getLandetxeaId()==castOther.getLandetxeaId())
 && (this.getEskaintzaId()==castOther.getEskaintzaId());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getLandetxeaId();
         result = 37 * result + this.getEskaintzaId();
         return result;
   }   


}


