package model;
// Generated 04-ene-2016 15:44:54 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Eskaintza generated by hbm2java
 */
public class Eskaintza  implements java.io.Serializable {


     private EskaintzaId id;
     private Date hasieraData;
     private Date amaieraData;
     private float prezioa;

    public Eskaintza() {
    }

    public Eskaintza(EskaintzaId id, Date hasieraData, Date amaieraData, float prezioa) {
       this.id = id;
       this.hasieraData = hasieraData;
       this.amaieraData = amaieraData;
       this.prezioa = prezioa;
    }
   
    public EskaintzaId getId() {
        return this.id;
    }
    
    public void setId(EskaintzaId id) {
        this.id = id;
    }
    public Date getHasieraData() {
        return this.hasieraData;
    }
    
    public void setHasieraData(Date hasieraData) {
        this.hasieraData = hasieraData;
    }
    public Date getAmaieraData() {
        return this.amaieraData;
    }
    
    public void setAmaieraData(Date amaieraData) {
        this.amaieraData = amaieraData;
    }
    public float getPrezioa() {
        return this.prezioa;
    }
    
    public void setPrezioa(float prezioa) {
        this.prezioa = prezioa;
    }




}


