package model;
// Generated 04-ene-2016 15:44:54 by Hibernate Tools 4.3.1



/**
 * Galdera generated by hbm2java
 */
public class Galdera  implements java.io.Serializable {


     private GalderaId id;
     private String testua;

    public Galdera() {
    }

    public Galdera(GalderaId id, String testua) {
       this.id = id;
       this.testua = testua;
    }
   
    public GalderaId getId() {
        return this.id;
    }
    
    public void setId(GalderaId id) {
        this.id = id;
    }
    public String getTestua() {
        return this.testua;
    }
    
    public void setTestua(String testua) {
        this.testua = testua;
    }




}


