package model;
// Generated 04-ene-2016 15:44:54 by Hibernate Tools 4.3.1



/**
 * GalderaId generated by hbm2java
 */
public class GalderaId  implements java.io.Serializable {


     private int galderaId;
     private int inkestaId;

    public GalderaId() {
    }

    public GalderaId(int galderaId, int inkestaId) {
       this.galderaId = galderaId;
       this.inkestaId = inkestaId;
    }
   
    public int getGalderaId() {
        return this.galderaId;
    }
    
    public void setGalderaId(int galderaId) {
        this.galderaId = galderaId;
    }
    public int getInkestaId() {
        return this.inkestaId;
    }
    
    public void setInkestaId(int inkestaId) {
        this.inkestaId = inkestaId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof GalderaId) ) return false;
		 GalderaId castOther = ( GalderaId ) other; 
         
		 return (this.getGalderaId()==castOther.getGalderaId())
 && (this.getInkestaId()==castOther.getInkestaId());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getGalderaId();
         result = 37 * result + this.getInkestaId();
         return result;
   }   


}


