package model;
// Generated 04-ene-2016 15:44:54 by Hibernate Tools 4.3.1



/**
 * InkestaId generated by hbm2java
 */
public class InkestaId  implements java.io.Serializable {


     private int inkestaId;
     private String erabIzena;

    public InkestaId() {
    }

    public InkestaId(int inkestaId, String erabIzena) {
       this.inkestaId = inkestaId;
       this.erabIzena = erabIzena;
    }
   
    public int getInkestaId() {
        return this.inkestaId;
    }
    
    public void setInkestaId(int inkestaId) {
        this.inkestaId = inkestaId;
    }
    public String getErabIzena() {
        return this.erabIzena;
    }
    
    public void setErabIzena(String erabIzena) {
        this.erabIzena = erabIzena;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof InkestaId) ) return false;
		 InkestaId castOther = ( InkestaId ) other; 
         
		 return (this.getInkestaId()==castOther.getInkestaId())
 && ( (this.getErabIzena()==castOther.getErabIzena()) || ( this.getErabIzena()!=null && castOther.getErabIzena()!=null && this.getErabIzena().equals(castOther.getErabIzena()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getInkestaId();
         result = 37 * result + ( getErabIzena() == null ? 0 : this.getErabIzena().hashCode() );
         return result;
   }   


}


