package model;
// Generated 04-ene-2016 15:44:54 by Hibernate Tools 4.3.1



/**
 * Inkesta generated by hbm2java
 */
public class Inkesta  implements java.io.Serializable {


     private InkestaId id;
     private int deskribapena;

    public Inkesta() {
    }

    public Inkesta(InkestaId id, int deskribapena) {
       this.id = id;
       this.deskribapena = deskribapena;
    }
   
    public InkestaId getId() {
        return this.id;
    }
    
    public void setId(InkestaId id) {
        this.id = id;
    }
    public int getDeskribapena() {
        return this.deskribapena;
    }
    
    public void setDeskribapena(int deskribapena) {
        this.deskribapena = deskribapena;
    }




}


