package model;
// Generated 04-ene-2016 15:44:54 by Hibernate Tools 4.3.1



/**
 * Iruzkina generated by hbm2java
 */
public class Iruzkina  implements java.io.Serializable {


     private IruzkinaId id;

    public Iruzkina() {
    }

    public Iruzkina(IruzkinaId id) {
       this.id = id;
    }
   
    public IruzkinaId getId() {
        return this.id;
    }
    
    public void setId(IruzkinaId id) {
        this.id = id;
    }




}


