package model;
// Generated 04-ene-2016 15:44:54 by Hibernate Tools 4.3.1



/**
 * Landetxea generated by hbm2java
 */
public class Landetxea  implements java.io.Serializable {


     private int landetxeId;
     private String izena;
     private String helbidea;
     private String deskribapena;
     private String erabIzena;

    public Landetxea() {
    }

    public Landetxea(int landetxeId, String izena, String helbidea, String deskribapena, String erabIzena) {
       this.landetxeId = landetxeId;
       this.izena = izena;
       this.helbidea = helbidea;
       this.deskribapena = deskribapena;
       this.erabIzena = erabIzena;
    }
   
    public int getLandetxeId() {
        return this.landetxeId;
    }
    
    public void setLandetxeId(int landetxeId) {
        this.landetxeId = landetxeId;
    }
    public String getIzena() {
        return this.izena;
    }
    
    public void setIzena(String izena) {
        this.izena = izena;
    }
    public String getHelbidea() {
        return this.helbidea;
    }
    
    public void setHelbidea(String helbidea) {
        this.helbidea = helbidea;
    }
    public String getDeskribapena() {
        return this.deskribapena;
    }
    
    public void setDeskribapena(String deskribapena) {
        this.deskribapena = deskribapena;
    }
    public String getErabIzena() {
        return this.erabIzena;
    }
    
    public void setErabIzena(String erabIzena) {
        this.erabIzena = erabIzena;
    }




}


