package model;
// Generated 04-ene-2016 15:44:54 by Hibernate Tools 4.3.1



/**
 * Txangoa generated by hbm2java
 */
public class Txangoa  implements java.io.Serializable {


     private TxangoaId id;
     private String mota;
     private String deskribapena;

    public Txangoa() {
    }

    public Txangoa(TxangoaId id, String mota, String deskribapena) {
       this.id = id;
       this.mota = mota;
       this.deskribapena = deskribapena;
    }
   
    public TxangoaId getId() {
        return this.id;
    }
    
    public void setId(TxangoaId id) {
        this.id = id;
    }
    public String getMota() {
        return this.mota;
    }
    
    public void setMota(String mota) {
        this.mota = mota;
    }
    public String getDeskribapena() {
        return this.deskribapena;
    }
    
    public void setDeskribapena(String deskribapena) {
        this.deskribapena = deskribapena;
    }




}


