package model;
// Generated 04-ene-2016 15:44:54 by Hibernate Tools 4.3.1



/**
 * TxangoaId generated by hbm2java
 */
public class TxangoaId  implements java.io.Serializable {


     private String landetxeId;
     private int txangoaId;

    public TxangoaId() {
    }

    public TxangoaId(String landetxeId, int txangoaId) {
       this.landetxeId = landetxeId;
       this.txangoaId = txangoaId;
    }
   
    public String getLandetxeId() {
        return this.landetxeId;
    }
    
    public void setLandetxeId(String landetxeId) {
        this.landetxeId = landetxeId;
    }
    public int getTxangoaId() {
        return this.txangoaId;
    }
    
    public void setTxangoaId(int txangoaId) {
        this.txangoaId = txangoaId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof TxangoaId) ) return false;
		 TxangoaId castOther = ( TxangoaId ) other; 
         
		 return ( (this.getLandetxeId()==castOther.getLandetxeId()) || ( this.getLandetxeId()!=null && castOther.getLandetxeId()!=null && this.getLandetxeId().equals(castOther.getLandetxeId()) ) )
 && (this.getTxangoaId()==castOther.getTxangoaId());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getLandetxeId() == null ? 0 : this.getLandetxeId().hashCode() );
         result = 37 * result + this.getTxangoaId();
         return result;
   }   


}


